homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Auth Providers (default: legacy_api_password)
  auth_providers:
    - type: homeassistant

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Database Timezone
  time_zone: America/Detroit

  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
config:
          
default_config:

influxdb:
  host: 127.0.0.1
  port: 8086
  database: home_assistant
  username: admin
  password: admin

frontend:
  themes: !include_dir_merge_named themes

panel_iframe:
  influxdb:
    title: InfluxDB
    icon: mdi:database
    url: !secret url_influxdb
  grafana:
    title: Grafana
    icon: mdi:chart-pie
    url: !secret url_grafana

# Show the introduction message on startup.
introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  base_url: !secret url_base 
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret email_password_1

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
## Zigbee shut off in January by DTE for version 2.  Currently running both bridges with
## v1 reporting to hassio and v2 reporting to the DTE Insight app.
  - platform: dte_energy_bridge
    ip: 192.168.1.35
    version: 1

# Device Trackers
device_tracker:
  - platform: netgear
    password: !secret device_netgear

# Bulbs
#tuya:
#  username: !secret email
#  password: !secret email_password_1
#  country_code: 1
#  platform: smart_life

# Abode
abode:
  username: !secret email
  password: !secret email_password_2

# Weather
weather:
  - platform: darksky
    api_key: !secret api_darksky

# Text to speech
tts:
  - platform: google

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
