
# @TODO: README.md containing my infrastructure, images, layout, etc...
# @TODO: PiHole
# @TODO: Home Panel: News Stream
# @TODO: Home Pane: Tract Integration
# @TODO: Useful energy usage chart/report
# @TODO: Health Integration with Samsung Health
# @TODO: Health Panel: Steps w/ previous week/month/year comparisons
# @TODO: Remove "Do you want to save this password" message when logging in.
# @TODO: TV Guide integration
# @TODO: Automation: "Aziz light!" - Turn on all lights in the room.
# @TODO: Administrative: Backup databases.  Disaster recovery.
# @TODO: Weather Panel:
# 
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Auth Providers
  auth_providers:
    - type: homeassistant

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Database Timezone
  time_zone: America/Detroit

  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
config:

default_config:

lovelace:
  mode: yaml

custom_updater:
  card_urls:
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json

influxdb:
  host: 127.0.0.1
  port: 8086
  database: home_assistant
  username: !secret user_influxdb
  password: !secret pass_influxdb

frontend:
  themes: !include_dir_merge_named themes

panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-pie
    url: !secret url_grafana
  pihole:
    title: Pi-hole
    icon: mdi:pi-box
    url: !secret url_pihole

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  base_url: !secret url_base 
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Sensors
sensor:
  # Weather prediction
  # FIXME: yr Symbol for Home badge does not look like it's using current timezone. 
  - platform: yr
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
  - platform: darksky
    api_key: !secret api_darksky
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
## Zigbee shut off in January by DTE for version 2.  Currently running both bridges with
## v1 reporting to hassio and v2 reporting to the DTE Insight app.
#  - platform: dte_energy_bridge
#    ip: 192.168.1.35
#    version: 1

# Device Trackers
device_tracker:
  - platform: netgear
    password: !secret device_netgear

# Bulbs
tuya:
  username: !secret email
  password: !secret email_password_1
  country_code: 1
  platform: 'tuya'

# Abode
abode:
  username: !secret email
  password: !secret email_password_2

# Weather
weather:
  - platform: darksky
    name: Weather
    units: us
    api_key: !secret api_darksky

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret